language: scala
sudo: false
dist: trusty
scala:
- 2.10.7
- 2.11.12
- 2.12.8
- 2.13.0-RC3
matrix:
  include:
  - scala: 2.12.8
    jdk: oraclejdk11
jdk:
- oraclejdk8
addons:
  postgresql: '9.3'
before_script:
- psql -c "CREATE ROLE squeryl WITH SUPERUSER LOGIN PASSWORD 'squeryl';" -U postgres
- psql -c "CREATE DATABASE squeryl;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO squeryl@"localhost"IDENTIFIED BY "squeryl";FLUSH PRIVILEGES;'
  -uroot
- mysql -e "CREATE DATABASE squeryl;" -usqueryl -psqueryl
- cp org.squeryl.tests.cfg.travis org.squeryl.tests.cfg
script:
- sbt "++${TRAVIS_SCALA_VERSION}!" test:compile
- rm -r src/test/scala/org/squeryl/oracle/
- rm -r src/test/scala/org/squeryl/mssql/
- sbt "++${TRAVIS_SCALA_VERSION}!" test
env:
  global:
  - secure: B/esoBi0gr3+/83hoVYfWrcQtOtVoBwI4qK7PjDeH89gV1tiyNUOp/E9+Lxt1RyJ4kQuiFaA241Toshy69f9AyUL4NCUo42noYEX7v66VppkAY3MfrCPKGAN9/urQF/ZELFiQblmAX3UzD91xluFzHjYpLcRDYe0vtYWN8EqJLw=
  - secure: BFWLPui/MHNHvWcpePTagUsHqnt3wqbJILgZuSFcKE0yPuydJzgoi5DNake/5rvGYKdyC6nCj6T8nShCNIXqOPSV5JL2gWaPbMrNxquXDy4CUy4zeAMHHrWO314ft2Xoa7zr6M+KeWpVAR/dEIIncjFNbhO3kDAgFPn4Vqm5z+w=
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
