language: scala
sudo: false
scala:
- 2.10.6
- 2.11.11
matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk8
  - scala: 2.13.0-M2
    jdk: oraclejdk8
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.4
    jdk: oraclejdk9
    before_install:
    - echo "sbt.version=1.0.0" > project/build.properties
jdk:
- openjdk7
addons:
  postgresql: '9.3'
before_script:
- psql -c "CREATE ROLE squeryl WITH SUPERUSER LOGIN PASSWORD 'squeryl';" -U postgres
- psql -c "CREATE DATABASE squeryl;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO squeryl@"localhost"IDENTIFIED BY "squeryl";FLUSH PRIVILEGES;'
  -uroot
- mysql -e "CREATE DATABASE squeryl;" -usqueryl -psqueryl
- cp org.squeryl.tests.cfg.travis org.squeryl.tests.cfg
script:
- sbt ++${TRAVIS_SCALA_VERSION} test:compile
- rm -r src/test/scala/org/squeryl/oracle/
- rm -r src/test/scala/org/squeryl/mssql/
- sbt ++${TRAVIS_SCALA_VERSION} test
env:
  global:
  - secure: B/esoBi0gr3+/83hoVYfWrcQtOtVoBwI4qK7PjDeH89gV1tiyNUOp/E9+Lxt1RyJ4kQuiFaA241Toshy69f9AyUL4NCUo42noYEX7v66VppkAY3MfrCPKGAN9/urQF/ZELFiQblmAX3UzD91xluFzHjYpLcRDYe0vtYWN8EqJLw=
  - secure: BFWLPui/MHNHvWcpePTagUsHqnt3wqbJILgZuSFcKE0yPuydJzgoi5DNake/5rvGYKdyC6nCj6T8nShCNIXqOPSV5JL2gWaPbMrNxquXDy4CUy4zeAMHHrWO314ft2Xoa7zr6M+KeWpVAR/dEIIncjFNbhO3kDAgFPn4Vqm5z+w=
